name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd lol-items
        npm install --legacy-peer-deps

    - name: Build
      run: |
        cd lol-items
        npm run build

    - name: Copy CNAME file
      run: cp CNAME lol-items/build/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: lol-items/build

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        timeout: 600000
        error_count: 10
        reporting_interval: 5000
        artifact_name: github-pages
        preview: false
